### ISSUE TITLE
YoURLs

### ISSUE THREAD

**Issue by joshp23** [LouisT/KiwiIRC-Plugins#1]
The Self Hosted application [YoURLs](https://github.com/YOURLS/YOURLS) url shortener a nice api and a [plugin](https://github.com/YOURLS/API-action) for adding custom api calls. 

I see that goo.gl is in the list here, interested in cobbling together something for YoURLs?

**Comment by LouisT** [comment]
I had previously looked into this, but the API for YOURLS seemed quite cumbersome. I didn't see a way to use an API key to be used from the client side (browser), only from the server side. If I'm incorrect can you provide me with a location of the docs on how to do this? Perhaps I could do something then.

**Comment by joshp23** [comment]
A regular request uses `username` and `password` variables in an [api](https://yourls.org/#API) call that can be done in the browser with ajax GET and jsonp formatting. That link has a basic example using json formatting, which creates problems with Same Origin policy issues.

The api key is merely put in as `signature` in the place of  `username` and `password`. [source](https://github.com/YOURLS/YOURLS/wiki/PasswordlessAPI) 

Here's an example of that as a function where `result` is the id of some div:
```
// CONFIG: Full path to YOURLS API
var api_url  = 'https://sho.rt/yourls-api.php';
// CONFIG: YOURLS API key.
var apikey = 'notTheRealSecret';

function shortenYOURLS(longUrl) {
	$.get( api_url, {
			signature: api_key,
			action: 'shorturl', 
			format: 'jsonp', 
			url: longUrl
			},
  	   	function(data) {
  	   		$(result).html(data.shorturl)
			},
		'jsonp'
		);
};

```
The api key itself ~~could~~ should be hit with MD5 using [JavaScript-MD5](https://github.com/blueimp/JavaScript-MD5/). So, after calling that script, one could use something like this:

```
function shortenYOURLS(longUrl) {
	function time() {
		var timestamp = Math.floor(new Date().getTime() / 1000);
		return timestamp;
		}
	function hkey() {
		var con = time() + '' + api_key;
		hash = md5(con);
		return hash;
		}
	$.get( api_url, {
			timestamp: time(),
			signature: hkey(),
			action: 'shorturl', 
			format: 'jsonp', 
			url: longUrl
			},
  	   	function(data) {
  	   		$(result).html(data.shorturl)
			},
		'jsonp'
		);
};
```
It is worth noting that, while the above examples work well, there's a good argument for using json formatting and POST instead of GET, and this can be accomplished by changing the obvious in the above examples, and adding the following to the YOURLS `.htaccess` file.

```
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT"
```

Further, there seems to be a decent javascript client already written up [here](https://github.com/neocotic/yourls-api) that could be hosted on, and called from the YOURLS installation along with the md5. i.e., 
```
<script src="https://sho.rt/client/md5.min.js"></script>
<script src="https://sho.rt/client/yourls.min.js"></script>
```
The yourls-api.js client ~~is going~~ _has just gone_ through an overhaul, and ~~doesn't currently support~~ _effortlessly supports_ time stamping the signature, however it does not, yet, seem to support POST.

I'm pretty green with javascript, but I have been working this out as I go, and I really don't know the kiwi stuff at all. I've been looking over the code for the google url shortener, and would love the same functionality as that but with YOURLS. What do you think?

**EDITED 11-23**

**Comment by joshp23** [comment]
So, after playing with this for a bit, this works just fine from the browser via a regular html form with `id='YOURLS'` and text input `name='url'` with no problem.
```
<script>
	// Attach a submit handler to the form
	$( "#YOURLS" ).submit(function() {

		// YOURLS Config data
		var api_url = 'https://sho.rl/yourls-api.php';
		var api_key = 'some42secret';
		
		event.preventDefault();
		$.get( api_url , { 
				signature: api_key, 
				action: 'shorturl', 
				format: 'jsonp', 
				url: $('[name=url]').val() },
	  	   	function(data) {
				console.log(data.shorturl) },
			'jsonp'
		);
	});
</script>
```

The yourls-api.js is totally unnecessary for something this basic. 

As opposed to php's native functions, the blueimp md5 script and the call to YOURLS with its resultant data seems to fail. SSL makes that a bit trivial.

So, this seems simple enough for a plugin, yes?

**Comment by joshp23** [comment]
Updated my comment above.

**Comment by LouisT** [comment]
Okay, this all seems doable, I'll look into it more when I get the chance (probably tomorrow some time) however I don't have an active YOURLS installation myself. I'll have to look into setting one up possibly first.

**Comment by joshp23** [comment]
Hey, that's great! 

Setting up YOURLS is trivial, however I can give you an api key and credentials for mine if you would like.

**Comment by joshp23** [comment]
Hey, that's great!

Setting up YOURLS is trivial, however I can give you an api key and credentials for mine if you would like.

_updated my comment above_

**Comment by joshp23** [comment]
Were you able to get anywhere on this?
